name: scribe
description: Blog from ZeroNetX Team.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.5
  reading_time: ^2.0.0
  timeago: ^3.3.0
  zeronet_ws: 0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true